title: Fangkai Li's Homepage
page-top-title: Li Fangkai
top-section-bg-text: Fangkai Li's Homepage
home-subtitle: Li Fangkai&ensp;|&ensp;李方凯
copyright-text: '&copy; Li Fangkai 2024-2025. All Rights Reserved.'
